// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsYdjh3mgiaXEArPiF3_gTzQpjHRl2KAE',
    appId: '1:465625701891:web:677b3b422dacc2fc513836',
    messagingSenderId: '465625701891',
    projectId: 'tallerflutter-70dc4',
    authDomain: 'tallerflutter-70dc4.firebaseapp.com',
    storageBucket: 'tallerflutter-70dc4.firebasestorage.app',
    measurementId: 'G-TN28W8RB1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTt1YA4Y_ZzwM4KNdO_QSas92Gr10X3a0',
    appId: '1:465625701891:android:472eb58bd82ae30a513836',
    messagingSenderId: '465625701891',
    projectId: 'tallerflutter-70dc4',
    storageBucket: 'tallerflutter-70dc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ctPA5NB0mTIWDeRnmcQS37XUJR5YZ-A',
    appId: '1:465625701891:ios:5bb8256b1b436d81513836',
    messagingSenderId: '465625701891',
    projectId: 'tallerflutter-70dc4',
    storageBucket: 'tallerflutter-70dc4.firebasestorage.app',
    iosBundleId: 'com.example.miniRedSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ctPA5NB0mTIWDeRnmcQS37XUJR5YZ-A',
    appId: '1:465625701891:ios:5bb8256b1b436d81513836',
    messagingSenderId: '465625701891',
    projectId: 'tallerflutter-70dc4',
    storageBucket: 'tallerflutter-70dc4.firebasestorage.app',
    iosBundleId: 'com.example.miniRedSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsYdjh3mgiaXEArPiF3_gTzQpjHRl2KAE',
    appId: '1:465625701891:web:e29e2891fd9aadd8513836',
    messagingSenderId: '465625701891',
    projectId: 'tallerflutter-70dc4',
    authDomain: 'tallerflutter-70dc4.firebaseapp.com',
    storageBucket: 'tallerflutter-70dc4.firebasestorage.app',
    measurementId: 'G-K6Y25CDF3W',
  );

}